[tool.black]
line-length = 88

[tool.ruff]
line-length = 88
include = ["*.ipynb"]

[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.ruff.lint.isort]
force-sort-within-sections = true

[tool.mypy]
ignore_missing_imports = true
